### ISSUE TITLE
Error in UseMehod

### ISSUE THREAD

**Issue by Koni2020** [jasonleebrown/machisplin#9]
Hello, I got following error during the process. 
![f9dcafad001341df6cfff20530d203e](https://user-images.githubusercontent.com/74965981/157583543-8580651b-0bca-4688-a40e-e53af5b75a85.png)
Recently, we intepolated different climatic dataset of temperature . However, we found that there is a error when distribution of the dataset is extreme distribution. 
![1646883399(1)](https://user-images.githubusercontent.com/74965981/157583573-09a9d12d-fb86-4562-b06f-29f8cb7b3cf8.png)
The asterisk dataset was able to interpolate, while the circle dataset cannot.  It seems the machin learn is sensitive to the distribution of the dataset. How to solve this bug? Could you please help? Thanks.

**Comment by geogvanni** [comment]
Hola, te respondo en español. Yo tuve el mismo problema, interpole datos mensuales de temperaturas y unos meses si me los interpoló sin problemas pero hubo otros que me marcaba ese error. Lo que hicimos para poder interpolar fue que la base de datos de los meses que no pude interpolar los multiplique por X valor (ejemplo por 2 o 3 o 4 etc) e intente interpolar de nuevo, tuve que hacer varias pruebas para ver con que valores me podía interpolar, tuve éxito con valores altos como 10, 12 y 15. Una vez que se genero mi interpolación dividí el ráster resultante entre el valor que multiplique (esto en algebra de mapas) y así pude solucionar este problema. 
Quizá no sea el método adecuado para solucionar esto pero fue la única opción que tuve .

**Comment by Koni2020** [comment]
> Hola, te respondo en español. Yo tuve el mismo problema, interpole datos mensuales de temperaturas y unos meses si me los interpoló sin problemas pero hubo otros que me marcaba ese error. Lo que hicimos para poder interpolar fue que la base de datos de los meses que no pude interpolar los multiplique por X valor (ejemplo por 2 o 3 o 4 etc) e intente interpolar de nuevo, tuve que hacer varias pruebas para ver con que valores me podía interpolar, tuve éxito con valores altos como 10, 12 y 15. Una vez que se genero mi interpolación dividí el ráster resultante entre el valor que multiplique (esto en algebra de mapas) y así pude solucionar este problema. Quizá no sea el método adecuado para solucionar esto pero fue la única opción que tuve .

**Comment by Koni2020** [comment]
Thanks to your reply. I think this kind of error may be related to data distribution or error data. For example, the temperature will hard excced 40 degree. However, if your dataset exsit abnormal value (50 degree) in node, it may get a error.  Therefore, i check my dataset and drop the abnormal value based on Tukey test. Then, iterpolate the dataset again. It works well.

**Comment by geogvanni** [comment]
Gracias por la respuesta, voy a hacer este proceso que mencionas para hacer de nuevo mi interpolación.
saludos.
